--- spatial window navigation
bind = hs.hotkey.bind
local wf_space = hs.window.filter.new(nil, "wf-SPACE"):setCurrentSpace(true):setDefaultFilter({})
bind({ "cmd" }, "k", "focus ↑", function()
	wf_space:focusWindowNorth(nil, true, true)
end)
bind({ "cmd" }, "l", "focus ↓", function()
	wf_space:focusWindowSouth(nil, true, true)
end)
bind({ "cmd" }, "j", "focus ←", function()
	wf_space:focusWindowWest(nil, true, true)
end)
bind({ "cmd" }, "ö", "focus →", function()
	wf_space:focusWindowEast(nil, true, true)
end)
-- bind({ "cmd" }, "l", "focus behind", function()
-- wf_space:focusWindowBehind(nil, true, true)
-- end)
-- bind(HYPER, "q", "send to back", function()
-- hs.window.frontmostWindow():sendToBack()
-- end)
